### ISSUE TITLE
Cannot create new line (改行) while writing comments

### ISSUE THREAD

**Issue by HelloKashif** [givlink/giv-app#11]

**Comment by naotakanishiyama** [comment]
投稿されているThanks Cardにコメントを入力する際、改行ができないため文章が読みづらい。
したがって、コメントを改行できるように修正する。

**Comment by HelloKashif** [comment]
Probably this line causing issue: https://github.com/givlink/giv-app/blob/master/pages/posts/_id/index.vue#L132

this might need to enable `event.preventDefault()`

**Comment by HelloKashif** [comment]
Sasakawa-san kindly fixed this already. Closing
