### ISSUE TITLE
Display order of Thanks Card (Thanks Cardの表示順番)

### ISSUE THREAD

**Issue by naotakanishiyama** [givlink/giv-app#18]
When we click さらに読み込む on timeline page below, TCs are not shown properly with timestamp.
（タイムラインの下部”さらに読み込む”をクリックすると、Thanks Cardの表示順番が時系列順番でなくなる）

**Comment by HelloKashif** [comment]
This is fixed now. Please check

**Comment by naotakanishiyama** [comment]
Yes, I've confirmed. Thanks!!
