### ISSUE TITLE
Date of the Thanks Card(Thanks Cardの日程)

### ISSUE THREAD

**Issue by naotakanishiyama** [givlink/giv-app#19]
Date of the TC is wrong.
（TCの日程が間違っています。添付画像だと全て同じ日付に変更されています。）
![IMG_4736](https://user-images.githubusercontent.com/60317544/118443472-e4312b80-b726-11eb-9378-7dfee20a2900.PNG)

**Comment by HelloKashif** [comment]
I think these were just some old notifications created on that same date. So dates are not wrong they are just junk notifications. Lets delete those.
