### ISSUE TITLE
Cannot open お知らせ

### ISSUE THREAD

**Issue by naotakanishiyama** [givlink/giv-app#20]
When a member try to write a TC and click on お知らせ, white page is shown.
（Thanks Cardを書こうとお知らせ欄をクリックすると、真っ白画面になる）
This error is from 山口san. https://members.giv.link/users/b0c2c39b-73b2-4355-9e2f-e36391701537

![image](https://user-images.githubusercontent.com/60317544/118624957-8ffc7900-b804-11eb-8b84-eb867785f417.png)

**Comment by indienuggets** [comment]
@naotakanishiyama san this is fixed now. Please recheck

**Comment by HelloKashif** [comment]
@naotakanishiyama san this is fixed now. Please recheck
